# Generated by Django 4.2.7 on 2023-11-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100, unique=True)),
                ('datetime', models.CharField(max_length=100, unique=True)),
                ('congestion_level', models.CharField(max_length=50)),
            ],
        ),
    ]
