# Generated by Django 4.2.7 on 2023-11-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='AI_nodjango/images/areas.png', upload_to='')),
            ],
        ),
    ]
