# Generated by Django 4.2.7 on 2023-11-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagefile',
            name='image',
            field=models.ImageField(default='D:/forecast_image', upload_to=''),
        ),
    ]
