# Generated by Django 4.2.7 on 2023-11-13 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0002_alter_imagefile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageFile',
        ),
    ]
